services:
  nginx-static:
    image: nginx:1.29.0-alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro

  nginx-proxy:
    image: nginx:1.29.0-alpine
#    ports:
#      - "80:80"     # HTTP → redirect
#      - "443:443"   # HTTPS termination
    volumes:
      - ./nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key:ro
