name: Generate Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
          
    - name: Run docgen test and build
      working-directory: config-docgen
      run: ./mvnw package -DskipTests 


    - name: create frontmatter
      run: |
        cat << EOF > config.markdown
        ---
        layout: page
        title: Config
        permalink: /config/
        ---
        EOF

    - name: run docgen on src
      run: java -jar config-docgen/target/sensepitch-edge-config-docgen-1.0-SNAPSHOT-with-dependencies.jar ./src/main/java/org/sensepitch/edge | tee -a config.markdown